name: Build

on:
  pull_request:
    branches: [main]
  push:
    tags: [0.*]

jobs:
  Build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch dependencies
        run: |
          sudo add-apt-repository ppa:tkchia/build-ia16
          sudo apt update
          sudo apt install gcc-ia16-elf libi86-ia16-elf -y
          git fetch --depth=1 origin +refs/tags/*:refs/tags/* || echo
          git submodule update --init

      - name: Build for release
        run: |
          make clean && make
          mkdir release
          mv bin release/
          mv lib release/

      - name: Build for debug
        run: |
          make clean && make LOGS=1
          mkdir debug
          mv bin debug/
          mv lib debug/

      - name: Prepare release info
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git tag -l --format='%(contents:subject)' ${{ github.ref_name }} | sed -r "s/^.+: //" > bin/RELEASE.md
  
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: andrea
          path: |
            release
            debug
            libman

  Release:

    runs-on: ubuntu-latest
    needs: Build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Fetch build output
        uses: actions/download-artifact@v3
        with:
          name: andrea
          
      - name: Prepare archive
        run: |
          zip -r andrea-${{ github.ref_name }}.zip release debug libman

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.ref_name }}
          body_path: bin/RELEASE.md
          files: andrea-${{ github.ref_name }}.zip
