name: Build

on:
  pull_request:
    branches: [main]
  push:
    tags: [0.*]

jobs:
  Build:

    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fetch dependencies
        run: |
          sudo add-apt-repository ppa:tkchia/build-ia16
          sudo apt update
          sudo apt install gcc-ia16-elf libi86-ia16-elf -y
          git fetch --depth=1 origin +refs/tags/*:refs/tags/* || echo
          git submodule update --init

      - name: Build for release
        run: |
          make clean && make
          mkdir -p release/lib common/lib
          mv bin release/
          mv lib/*.exe.a release/bin/
          mv lib/libandrea* release/lib/
          cp -r include common/
          mv lib/*.ld common/lib/
          mv lib/andrea-modstart.a common/lib/

      - name: Build for debug
        run: |
          make clean && make LOGS=1
          mkdir -p debug/lib
          mv bin debug/
          mv lib/*.exe.a debug/bin/
          mv lib/libandrea* debug/lib/
          rm -rf libman/andrea/__pycache__

      - name: Prepare release info
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          git tag -l --format='%(contents:subject)' ${{ github.ref_name }} | sed -r "s/^.+: //" > common/RELEASE.md
  
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: andrea
          path: |
            common
            release
            debug
            libman

  Release:

    runs-on: ubuntu-latest
    needs: Build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Fetch build output
        uses: actions/download-artifact@v4
        with:
          name: andrea
          
      - name: Prepare archive
        run: |
          rm -rf release/bin debug/bin
          cp -r common/* release/
          cp -r libman release/
          cd release
          zip -r ../andrea-${{ github.ref_name }}.zip lib libman include
          cd ..
          cp -r common/* debug/
          cp -r libman debug/
          cd debug
          zip -r ../andrea-${{ github.ref_name }}-debug.zip lib libman include
          cd ..

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: Version ${{ github.ref_name }}
          body_path: common/RELEASE.md
          files: |
            andrea-${{ github.ref_name }}.zip
            andrea-${{ github.ref_name }}-debug.zip
